### ISSUE TITLE
On branches

### ISSUE THREAD

**Issue by plehegar** [w3c/using-github#1]
If you have only one draft with one version: just use gh-pages and delete master.

If you have more than one branch, you'll need to use https://github.com/webspecs/the-index to publish them all since gh-pages won't do the trick. See also https://github.com/webspecs/publican/issues/18

**Comment by tripu** [comment]
Addressed [here](https://w3c.github.io/specs.html) and [here (&ldquo;using `gh-pages`&rdquo;)](https://w3c.github.io/faq.html).
