### ISSUE TITLE
Using gitbot on consortium IRC channels

### ISSUE THREAD

**Issue by AFBarstow** [w3c/using-github#14]
gitbot is used in the #testing IRC channel and I'd like to use it some other channels. How do I go about getting that to work? Do I submit a request to some person/list? Is there some guide I need to follow?

**Comment by tripu** [comment]
@AFBarstow, maybe this helps? [_Re: Gitbot? from Michael[tm] Smith on 2014-12-29 (public-test-infra@w3.org from October to December 2014)_](https://lists.w3.org/Archives/Public/public-test-infra/2014OctDec/0045.html)

**Comment by tripu** [comment]
@AFBarstow: as @sideshowbarker pointed out in the e-mail I mentioned above, it's a service provided by GH.

Visit `https://github.com/w3c/<PROJECT_NAME>/settings/hooks/new?service=irc` to set it up for `<PROJECT_NAME>`.
