### ISSUE TITLE
Check precise GH admin vs owner rights

### ISSUE THREAD

**Issue by darobin** [w3c/using-github#8]
We have noticed in the past that granting admin rights on a repo to a team had broader effects in that it enabled people to do things to the parent organisation.

This may have been fixed since — it is worth checking whether we could reinstate this.

**Comment by tripu** [comment]
@darobin: do you think the [improved organization permissions](https://help.github.com/articles/about-improved-organization-permissions/) that were [rolled out recently](https://github.com/blog/2064-new-organization-permissions-now-available) solve this?

**Comment by tripu** [comment]
After those changes, a particular team (thus its members) is given access to a particular repo [in three levels: _admin_, _write_, _read_](https://help.github.com/articles/managing-team-access-to-an-organization-repository/) ([example](https://github.com/w3c/using-github/settings/collaboration)). I understand that those affect only that repo; not the parent organisation.
