### ISSUE TITLE
Provide a CONTRIBUTING.md.example file

### ISSUE THREAD

**Issue by astorije** [w3c/using-github#9]
If this repo is meant to contain all the guidelines to edit specs, then spec/group repositories should refer to it.
The best way to do so is to add a `CONTRIBUTING.md` file in each repository as it adds a disclaimer note every time someone opens an issue or a pull request.
To ease with this process, this repository should contain a template of such a file to include in other repositories. It should be kept super simple because it is unlikely to be updated in repositories using it, so best to just include a link to this repo.

**Comment by wayneca** [comment]
Here's what the Web NFC Community Group is using.[CONTRIBUTING.md](https://github.com/w3c/web-nfc/blob/gh-pages/CONTRIBUTING.md) and [LICENSE.md](https://github.com/w3c/web-nfc/blob/gh-pages/LICENSE.md). That Community Group doesn't have any software, just specs and other documents.
